id = "quarto"
name = "Quarto"
version = "0.1.0"
schema_version = 1
authors = ["Chris Kennedy <chrisken@gmail.com>"]
description = "Quarto authoring for Zed with Pandoc-aware syntax highlighting"
repository = "https://github.com/ck37/zed-quarto-extension"
languages = ["languages/quarto", "languages/pandoc_markdown_inline"]

[grammars.pandoc_markdown]
repository = "https://github.com/ck37/tree-sitter-pandoc-markdown"
commit = "40ee81adf88b8d85eef939da6efcb6593dc4324a"
path = "tree-sitter-pandoc-markdown"

[grammars.pandoc_markdown_inline]
repository = "https://github.com/ck37/tree-sitter-pandoc-markdown"
commit = "40ee81adf88b8d85eef939da6efcb6593dc4324a"
path = "tree-sitter-pandoc-markdown-inline"
