id = "quarto"
name = "Quarto"
version = "0.1.0"
schema_version = 1
authors = ["Chris Kennedy <chrisken@gmail.com>"]
description = "First-class Quarto authoring for Zed with syntax highlighting and language-server support"
repository = "https://github.com/ck37/zed-quarto-extension"

[grammars.pandoc_markdown]
repository = "https://github.com/ck37/tree-sitter-pandoc-markdown"
commit = "c325990ee8824f9746303d6785170ac43fcc8a93"
path = "tree-sitter-pandoc-markdown"

[language_servers.quarto]
name = "Quarto Language Server"
languages = ["Quarto"]

[[capabilities]]
kind = "process:exec"
command = "quarto"
args = ["language-server"]
