id = "quarto"
name = "Quarto"
version = "0.1.0"
schema_version = 1
authors = ["Chris Kennedy <chrisken@gmail.com>"]
description = "Quarto authoring for Zed with Pandoc-aware syntax highlighting"
repository = "https://github.com/ck37/zed-quarto-extension"

[grammars.pandoc_markdown]
repository = "https://github.com/ck37/tree-sitter-pandoc-markdown"
commit = "17677df1749f9489032f8757192cd19231563186"
path = "tree-sitter-pandoc-markdown"

[grammars.pandoc_markdown_inline]
repository = "https://github.com/ck37/tree-sitter-pandoc-markdown"
commit = "17677df1749f9489032f8757192cd19231563186"
path = "tree-sitter-pandoc-markdown-inline"
