id = "quarto"
name = "Quarto"
version = "0.2.0"
schema_version = 1
authors = ["Chris Kennedy <chrisken@gmail.com>"]
description = "Quarto authoring for Zed with tree-sitter-quarto grammar"
repository = "https://github.com/ck37/zed-quarto-extension"
languages = ["languages/quarto"]

[grammars.quarto]
repository = "https://github.com/ck37/tree-sitter-quarto"
commit = "c9f444e88fc6f787c660bf52b0e23879a8fc66c2"
path = "grammars/quarto"
