id = "quarto"
name = "Quarto"
version = "0.2.0"
schema_version = 1
authors = ["Chris Kennedy <chrisken@gmail.com>"]
description = "Quarto authoring for Zed with tree-sitter-quarto grammar"
repository = "https://github.com/ck37/zed-quarto-extension"
languages = ["languages/quarto"]

[grammars.quarto]
path = "grammars/quarto"
