name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  RUSTFLAGS: -D warnings

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasip2
          components: clippy, rustfmt
          override: true
      - name: Clippy
        run: cargo clippy --all-features --all-targets
      - name: Rustfmt
        run: cargo fmt --all -- --check

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.87.0
          target: wasm32-wasip2
          override: true
      - name: Build
        run: cargo build --target wasm32-wasip2 --all-features
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Test (nextest)
        run: cargo nextest run --all-features --profile ci
